# Generated by Django 6.0.3 on 2026-03-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
